---
- name: Install Apache
  hosts: centos
  become: true

  vars:
    key: value

  vars_files:
    - vars/main.yml

  vars:
    proxy_vars:
      http_proxy: http://exmple-proxy:80/
      https_proxy: https:/example-proxy:80/

  environment:
    http_proxy: http://exmple-proxy:80/
    https_proxy: https:/example-proxy:80/

  handlers:
    - name: restart apache 
      service:
        name: httpd
        state: restarted
      notify: restart memcached
    
    - name: restart memcached
      service:
        name: memcached
        state: restarted

  tasks:
    - name: Add an environment variable to the remote user's shell
      lineinfile:
        dest: "~/.bash_profile"
        regexp: '^ENV_VAR= '
        line: 'ENV_VAR=value'
      become: false

    - name: Get the value of an environment variable
      shell: 'source ~/.bash_profile && echo $ENV_VAR'
      register: foo
      become: false

    - debug: msg="The variable is {{ foo.stdout }}"

    - name: Download a file
      get_url:
        url: http://ipv4.download.thkinkbroadband.com/20MB.zip
        dest: /tmp
      environment: proxy_vars

    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present
    
    - name: Copy test config file
      copy:
        src: files/test.conf
        dest: /etc/httpd/conf.d/test.conf
      notify: 
        - restart apache

    # - name: Make sure handlers are flushed immediately.
    #   meta: flush_handlers
    
    - name: Ensure Apache is running and starts at boot
      service:
        name: httpd
        state: started
        enabled: true
    
    - name: Eusure memcached is installed
      yum:
        name: memcached
        state: present
    
    - name: Ensure memcached is running and starts at boot
      service:
          name: memcached
          state: started
          enabled: true
